# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Daily Github-Trending

on:
#   workflow_dispatch: # Manually running a workflow

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

  schedule:
    - cron: "0 11 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run crawler
      run: |
        python crawler.py

    # Runs a set of commands using the runners shell
    - name: push to origin master
      run: |
        echo "start push"
        git config --global user.name "duanbiao2000"
        git config --global user.email "duanbiao2000@gmail.com"
        git pull --rebase
        git add markdowns/*.md
        git commit -m $(date '+%Y-%m-%d')
        git pull
        git push
